learning_log/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('learning_logs.urls', 'learning_logs'), namespace='learning_logs')),
    path('users/', include(('users.urls', 'users'), namespace='users'))

]

learning_logs/urls.py
"""Определяет схемы URL для learning_logs."""

from django.urls import path
from . import views

urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    #Page for displaying a list of topics
    path('topics/', views.topics, name='topics'),
    # Page for viewing posts on this topic
    path('topics/<topic_id>/', views.topic, name='topic'),
    # Page for adding a new theme
    path('new_topic/', views.new_topic, name='new_topic'),
    # new entry
    path('new_entry/<topic_id>/', views.new_entry, name='new_entry'),
    # edit entry
    path('edit_entry/<entry_id>', views.edit_entry, name='edit_entry'),
    path('delete_entry/<entry_id>/', views.delete_entry, name='delete_entry'),
    path('delete_topic/<topic_id>/', views.delete_topic, name='delete_topic'),


]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

urlpatterns = [

    path('login', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    # page register
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """Тема, которую изучает пользователь"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        '''Возвращает строковое представление модели'''
        return self.text


class Entry(models.Model):
    """Информация, изученная пользователем по теме"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField(blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        '''Возвращает текстовое представление модели'''
        if len(self.text) > 50:
            return self.text[:50] + '...'
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """Вывод списка тем"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи."""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Определяет новую тему"""
    if request.method != 'POST':
        # Данные не отправились, создается пустая форма
        form = TopicForm()
    else:
        # Данные отправились, обработать их
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
        return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Определяет новую запись"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # Данные не отправились, создается пустая форма
        form = EntryForm()
    else:
        # Данные отправились, обработать их
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Редактирование записей"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

@login_required
def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    entry.delete()
    return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

@login_required
def delete_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    topic.delete()
    return HttpResponseRedirect(reverse('learning_logs:topics'))

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm



def logout_view(request):
    """Завершает сеанс работы с приложением."""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """Page register"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
        # Выполнение входа и перенаправление на домашнюю страницу.
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>

    <title>Learning Log</title>

    <style>
    body {
    background-image: url({% static "learning_logs/фон.jpg"%});
    background-size: cover;
    background-attachment: fixed;
    }



    </style>
</head>
<body>

<!-- Фиксированная навигационная панель -->

<nav class="navbar fixed-top navbar-expand-lg navbar-light" style="background-color: #DCDCDC">
    <a class="navbar-brand" href="{% url 'learning_logs:index' %}"><b>Learning Log</b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
            aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav nav nav-pills">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:topics' %}"><b>Topics</b>
                    <span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link disabled"><b>Hello, {{ user.username }}.</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}"><b>Log out</b></a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}"><b>Register</b></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}"><b>Log in</b></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container" style="margin-top: 100px">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div> <!-- /container -->
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load crispy_forms_tags %}
{% block header %}

{% endblock header %}

{% block content %}
<div class="jumbotron" style="background-color: #E6E6FA">
    <h1 align="center" class="display-4"><em>{{ topic }}</em></h1>
    <hr class="my-3">
    <p class="lead">Edit entry from {{ entry.date_added|date:'M d, Y H:i' }}</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form|crispy }}
        <div align="right">
            <form action="{% url 'learning_logs:new_topic' %}">
                <button name="submit" class="btn btn-primary">Save changes</button>
            </form>
        </div>
    </form>
</div>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
<div class="jumbotron" style="background-color: #E6E6FA">
    <h1 align="center" class="display-4"><em>Track your learning</em></h1>
    <hr class="my-3">
    <p class="lead" align="center" >
        Create your own learning journal and list the topics studied.
        Each time you learn something new on a topic,
        make a note summarizing what you have learned.
    </p>
</div>
{% endblock header %}

{% block content %}

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load crispy_forms_tags %}
{% block header %}

{% endblock header %}

{% block content %}
<div class="jumbotron" style="background-color: #E6E6FA">
    <h1 align="center" class="display-4"><em>{{ topic }}</em></h1>
    <hr class="my-3">
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form|crispy }}
        <div align="right">
            <form action="{% url 'learning_logs:new_topic' %}">
                <button name="submit" class="btn btn-primary">Add entry</button>
            </form>
        </div>
    </form>
</div>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load crispy_forms_tags %}
{% block header %}

{% endblock header %}

{% block content %}
<div class="jumbotron" style="background-color: #E6E6FA">
    <p class="lead" align="center">Enter the title</p>
    <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
        {% csrf_token %}
        {{ form|crispy }}
        <div align="right">
            <button name="submit" class="btn btn-primary">Add topic</button>
        </div>
    </form>
</div>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}

{% endblock header %}

{% block content %}
<div class="jumbotron" style="background-color: #E6E6FA">
    <h1 align="center" class="display-4"><em>{{ topic }}</em></h1>
    <hr class="my-3">
    {% if entries %}
    <div align="right">
        <form action="{% url 'learning_logs:new_entry' topic.id %}">
            <button name="submit" class="btn btn-primary">Add a new entry</button>
            <a href="{% url 'learning_logs:delete_topic' topic.id %}"
               class="btn btn-danger" role="button">Delete topic</a>
        </form>
    </div>
    {% for entry in entries %}
    <div class="card" style="margin-top: 15px">
        <h5 class="card-header">{{ entry.date_added|date:'M d, Y H:i' }}</h5>
        <div class="card-body">
            <p class="card-text">{{ entry.text|linebreaks }}</p>
            <div align="right">
                <a href="{% url 'learning_logs:edit_entry' entry.id %}" class="btn btn-outline-secondary btn-sm">Edit
                    entry</a>
                <a href="{% url 'learning_logs:delete_entry' entry.id %}" class="btn btn-outline-danger btn-sm">Delete
                    entry</a>
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h4 align="center">There are no entries for this topic yet.</h4>
    <div align="center" style="margin-top: 20px">
        <form action="{% url 'learning_logs:new_entry' topic.id %}">
            <button name="submit" class="btn btn-primary">Add a new entry</button>
            <a href="{% url 'learning_logs:delete_topic' topic.id %}"
               class="btn btn-danger" role="button">Delete topic</a>
        </form>
    </div>
    {% endif %}
</div>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{% block header %}
{% endblock header %}

{% block content %}
<div class="jumbotron" style="background-color: #E6E6FA">
    <h1 align="center" class="display-4"><em>My topics</em></h1>
    <hr class="my-3">
    <ul>
        {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id %} ">{{ topic }}</a>
        </li>
        {% endfor %}
    </ul>
    <div align="right">
        <form action="{% url 'learning_logs:new_topic' %}">
            <button name="submit" class="btn btn-primary">Add a new topic</button>
        </form>
    </div>
</div>

{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load crispy_forms_tags %}
{% block header %}
{% endblock header %}

{% block content %}
<div class="jumbotron" style="background-color: #E6E6FA">
    <p class="display-4" align="center">Sign in</p>
    <hr class="my-3">
    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        {{ form|crispy }}
        <div align="right">
            <button name="submit" class="btn btn-primary">Log in</button>
        </div>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </form>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load crispy_forms_tags %}

{% block header %}

{% endblock header %}

{% block content %}
<div class="jumbotron" style="background-color: #E6E6FA">
    <p class="display-4" align="center">Register your account</p>
    <hr class="my-3">
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <div align="right">
            <button name="submit" class="btn btn-primary">Register</button>
        </div>
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
    </form>
</div>
{% endblock content %}